import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'PDF to Word Converter Online Free - Convert PDF to DOCX | PDF Prodigy',
  description: 'Convert PDF to Word (DOCX) online for free. Perfect text extraction, OCR support, and formatting preservation. No signup required. Convert PDF to editable Word documents instantly.',
  keywords: [
    'pdf to word converter',
    'convert pdf to word',
    'pdf to docx converter',
    'pdf to word online',
    'free pdf to word',
    'pdf to word converter free',
    'convert pdf to docx',
    'pdf to microsoft word',
    'pdf word converter',
    'online pdf to word',
    'pdf to editable word',
    'pdf text extraction',
    'pdf to word with formatting',
    'scanned pdf to word',
    'ocr pdf to word',
    'pdf to word accurate',
    'convert pdf to editable text',
    'pdf document converter',
    'pdf to word online free',
    'secure pdf to word',
    'batch pdf to word',
    'pdf to word no signup',
    'fast pdf to word conversion',
    'professional pdf converter',
    'pdf to word with images'
  ],
  authors: [{ name: 'PDF Prodigy Team' }],
  creator: 'PDF Prodigy',
  publisher: 'PDF Prodigy',
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: 'https://pdfprodigy.com/pdf-to-word',
    title: 'PDF to Word Converter Online Free - Convert PDF to DOCX',
    description: 'Convert PDF to Word (DOCX) online for free. Perfect text extraction, OCR support, and formatting preservation. No signup required.',
    siteName: 'PDF Prodigy',
    images: [
      {
        url: '/images/pdf-to-word-og.jpg',
        width: 1200,
        height: 630,
        alt: 'PDF to Word Converter Online Free - Convert PDF to DOCX',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'PDF to Word Converter Online Free - Convert PDF to DOCX',
    description: 'Convert PDF to Word (DOCX) online for free. Perfect text extraction, OCR support, and formatting preservation.',
    images: ['/images/pdf-to-word-twitter.jpg'],
    creator: '@pdfprodigy',
  },
  alternates: {
    canonical: 'https://pdfprodigy.com/pdf-to-word',
  },
  category: 'Productivity',
};
