import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'HTML to PDF Converter - Convert Web Pages & HTML Code to PDF Online | PDF Prodigy',
  description: 'Convert HTML to PDF online for free. Transform websites, HTML code, and HTML files into high-quality PDF documents. Preserve CSS styling, support JavaScript, mobile responsive conversion.',
  keywords: [
    'html to pdf',
    'convert html to pdf',
    'html to pdf converter',
    'website to pdf',
    'web page to pdf',
    'html file to pdf',
    'convert web page to pdf',
    'html code to pdf',
    'online html to pdf',
    'free html to pdf converter',
    'html to pdf online',
    'web to pdf converter',
    'webpage to pdf',
    'html document to pdf',
    'css to pdf',
    'javascript to pdf',
    'responsive html to pdf',
    'mobile webpage to pdf',
    'convert website to pdf online',
    'html to pdf with css',
    'html5 to pdf',
    'dynamic html to pdf',
    'web content to pdf',
    'save webpage as pdf',
    'print webpage to pdf'
  ].join(', '),
  authors: [{ name: 'PDF Prodigy' }],
  creator: 'PDF Prodigy',
  publisher: 'PDF Prodigy',
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  openGraph: {
    title: 'HTML to PDF Converter - Convert Web Pages & HTML Code to PDF',
    description: 'Convert HTML to PDF online for free. Transform websites, HTML code, and HTML files into high-quality PDF documents with preserved styling.',
    url: 'https://pdfprodigy.com/html-to-pdf',
    siteName: 'PDF Prodigy',
    images: [
      {
        url: '/images/html-to-pdf-og.jpg',
        width: 1200,
        height: 630,
        alt: 'HTML to PDF Converter Tool',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'HTML to PDF Converter - Convert Web Pages & HTML Code to PDF',
    description: 'Convert HTML to PDF online for free. Transform websites, HTML code, and HTML files into high-quality PDF documents.',
    images: ['/images/html-to-pdf-twitter.jpg'],
    creator: '@PDFProdigy',
  },
  alternates: {
    canonical: 'https://pdfprodigy.com/html-to-pdf',
  },
  category: 'PDF Tools',
  classification: 'HTML Conversion Tool',
  other: {
    'application-name': 'PDF Prodigy - HTML to PDF Converter',
    'msapplication-TileColor': '#ea580c',
    'theme-color': '#ea580c',
  },
};
