import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Unlock PDF Files - Remove Password Protection & Restrictions Online | PDF Prodigy',
  description: 'Unlock password-protected PDF files online for free. Remove user passwords, owner passwords, and restrictions like printing, copying, and editing. Secure PDF unlocking tool.',
  keywords: [
    'unlock pdf',
    'remove pdf password',
    'pdf password remover',
    'unlock password protected pdf',
    'remove pdf restrictions',
    'pdf unlock tool',
    'password protected pdf unlock',
    'remove pdf security',
    'unlock encrypted pdf',
    'pdf password recovery',
    'remove pdf permissions',
    'unlock pdf online',
    'free pdf unlock',
    'pdf password breaker',
    'remove pdf protection',
    'unlock secured pdf',
    'pdf restriction remover',
    'owner password removal',
    'user password removal',
    'print restriction removal',
    'copy restriction removal',
    'edit restriction removal',
    'pdf security remover',
    'unlock pdf files',
    'remove pdf encryption'
  ].join(', '),
  authors: [{ name: 'PDF Prodigy' }],
  creator: 'PDF Prodigy',
  publisher: 'PDF Prodigy',
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  openGraph: {
    title: 'Unlock PDF Files - Remove Password Protection & Restrictions Online',
    description: 'Unlock password-protected PDF files online for free. Remove passwords and restrictions from PDFs securely and instantly.',
    url: 'https://pdfprodigy.com/unlock-pdf',
    siteName: 'PDF Prodigy',
    images: [
      {
        url: '/images/unlock-pdf-og.jpg',
        width: 1200,
        height: 630,
        alt: 'PDF Unlock Tool - Remove Password Protection',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Unlock PDF Files - Remove Password Protection & Restrictions',
    description: 'Unlock password-protected PDF files online for free. Remove passwords and restrictions from PDFs securely.',
    images: ['/images/unlock-pdf-twitter.jpg'],
    creator: '@PDFProdigy',
  },
  alternates: {
    canonical: 'https://pdfprodigy.com/unlock-pdf',
  },
  category: 'PDF Tools',
  classification: 'PDF Security Tool',
  other: {
    'application-name': 'PDF Prodigy - PDF Unlock Tool',
    'msapplication-TileColor': '#dc2626',
    'theme-color': '#dc2626',
  },
};
