import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'PDF to PDF/A Converter - Archival Quality PDF Conversion Online | PDF Prodigy',
  description: 'Convert PDF to PDF/A format online for free. Create archival-quality documents that meet international standards for long-term preservation and compliance.',
  keywords: [
    'pdf to pdf/a',
    'pdf to pdfa converter',
    'pdf/a conversion',
    'archival pdf',
    'pdf archival format',
    'pdf/a online converter',
    'pdf to pdf/a online',
    'pdf archival conversion',
    'pdf/a compliance',
    'long term pdf preservation',
    'pdf/a-1',
    'pdf/a-2',
    'pdf/a-3',
    'iso 19005',
    'archival document format',
    'pdf preservation',
    'convert to pdf/a',
    'pdf/a validator',
    'archival quality pdf',
    'pdf compliance conversion',
    'institutional archival pdf',
    'pdf/a standard',
    'digital preservation pdf',
    'legal pdf archival',
    'regulatory pdf compliance'
  ].join(', '),
  authors: [{ name: 'PDF Prodigy' }],
  creator: 'PDF Prodigy',
  publisher: 'PDF Prodigy',
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  openGraph: {
    title: 'PDF to PDF/A Converter - Archival Quality PDF Conversion Online',
    description: 'Convert PDF to PDF/A format online for free. Create archival-quality documents for long-term preservation and compliance.',
    url: 'https://pdfprodigy.com/pdf-to-pdfa',
    siteName: 'PDF Prodigy',
    images: [
      {
        url: '/images/pdf-to-pdfa-og.jpg',
        width: 1200,
        height: 630,
        alt: 'PDF to PDF/A Converter - Archival Document Conversion',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'PDF to PDF/A Converter - Archival Quality PDF Conversion',
    description: 'Convert PDF to PDF/A format online for free. Create archival-quality documents for long-term preservation.',
    images: ['/images/pdf-to-pdfa-twitter.jpg'],
    creator: '@PDFProdigy',
  },
  alternates: {
    canonical: 'https://pdfprodigy.com/pdf-to-pdfa',
  },
  category: 'PDF Tools',
  classification: 'PDF Archival Conversion Tool',
  other: {
    'application-name': 'PDF Prodigy - PDF to PDF/A Converter',
    'msapplication-TileColor': '#16a34a',
    'theme-color': '#16a34a',
  },
};
