import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Scan to PDF - Convert Images & Documents to PDF Online | PDF Prodigy',
  description: 'Convert scanned documents and images to PDF online for free. Advanced OCR, auto-enhancement, and quality options. Upload photos or use camera scanning.',
  keywords: [
    'scan to pdf',
    'convert images to pdf',
    'document scanner',
    'photo to pdf',
    'image to pdf converter',
    'scan documents to pdf',
    'mobile scanner',
    'camera scan pdf',
    'ocr scanner',
    'document digitization',
    'paper to pdf',
    'scan app',
    'pdf scanner online',
    'image scanner pdf',
    'convert photos to pdf',
    'document scanning app',
    'jpeg to pdf',
    'png to pdf',
    'tiff to pdf',
    'multi page scanner',
    'batch scan pdf',
    'auto crop scanner',
    'text recognition pdf',
    'searchable pdf',
    'scanner with ocr'
  ].join(', '),
  authors: [{ name: 'PDF Prodigy' }],
  creator: 'PDF Prodigy',
  publisher: 'PDF Prodigy',
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  openGraph: {
    title: 'Scan to PDF - Convert Images & Documents to PDF Online',
    description: 'Convert scanned documents and images to PDF online for free. Advanced OCR, auto-enhancement, and professional quality output.',
    url: 'https://pdfprodigy.com/scan-to-pdf',
    siteName: 'PDF Prodigy',
    images: [
      {
        url: '/images/scan-to-pdf-og.jpg',
        width: 1200,
        height: 630,
        alt: 'Scan to PDF Tool - Convert Images and Documents',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Scan to PDF - Convert Images & Documents to PDF',
    description: 'Convert scanned documents and images to PDF online for free. OCR and auto-enhancement features included.',
    images: ['/images/scan-to-pdf-twitter.jpg'],
    creator: '@PDFProdigy',
  },
  alternates: {
    canonical: 'https://pdfprodigy.com/scan-to-pdf',
  },
  category: 'PDF Tools',
  classification: 'Document Scanning Tool',
  other: {
    'application-name': 'PDF Prodigy - Scan to PDF',
    'msapplication-TileColor': '#3b82f6',
    'theme-color': '#3b82f6',
  },
};
