import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Merge PDF Files Online Free - Combine Multiple PDFs | PDF Prodigy',
  description: 'Merge multiple PDF files into one document online for free. Easy drag & drop PDF merger tool. No signup required. Combine PDFs instantly with our secure online PDF merger.',
  keywords: [
    'merge pdf online',
    'combine pdf files',
    'pdf merger free',
    'join pdf files',
    'merge multiple pdfs',
    'pdf combiner online',
    'unite pdf documents',
    'consolidate pdf files',
    'pdf merge tool',
    'combine pdf online free',
    'merge pdf documents',
    'pdf joiner',
    'pdf concatenation',
    'merge pdf pages',
    'pdf file merger',
    'online pdf merger',
    'free pdf combiner',
    'pdf merge service',
    'pdf union tool',
    'pdf assembler',
    'pdf compilation tool',
    'merge pdf without watermark',
    'secure pdf merger',
    'fast pdf merge',
    'pdf merger no signup'
  ],
  authors: [{ name: 'PDF Prodigy Team' }],
  creator: 'PDF Prodigy',
  publisher: 'PDF Prodigy',
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: 'https://pdfprodigy.com/merge-pdf',
    title: 'Merge PDF Files Online Free - Combine Multiple PDFs',
    description: 'Merge multiple PDF files into one document online for free. Easy drag & drop PDF merger tool. No signup required. Secure and fast PDF merging.',
    siteName: 'PDF Prodigy',
    images: [
      {
        url: '/images/merge-pdf-og.jpg',
        width: 1200,
        height: 630,
        alt: 'Merge PDF Files Online - Free PDF Merger Tool',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Merge PDF Files Online Free - Combine Multiple PDFs',
    description: 'Merge multiple PDF files into one document online for free. Easy drag & drop PDF merger tool. No signup required.',
    images: ['/images/merge-pdf-twitter.jpg'],
    creator: '@pdfprodigy',
  },
  alternates: {
    canonical: 'https://pdfprodigy.com/merge-pdf',
  },
  category: 'Productivity',
};
