import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Protect PDF Files - Add Password Protection & Security Online | PDF Prodigy',
  description: 'Protect PDF files with passwords and security restrictions online for free. Add user passwords, owner passwords, and control printing, copying, editing permissions. Secure PDF encryption tool.',
  keywords: [
    'protect pdf',
    'pdf password protection',
    'add password to pdf',
    'secure pdf files',
    'pdf encryption',
    'password protect pdf',
    'pdf security',
    'protect pdf online',
    'add password pdf',
    'pdf protection tool',
    'encrypt pdf files',
    'pdf permissions',
    'pdf restrictions',
    'secure pdf online',
    'pdf access control',
    'user password pdf',
    'owner password pdf',
    'pdf print restrictions',
    'pdf copy restrictions',
    'pdf edit restrictions',
    'pdf form restrictions',
    'pdf annotation restrictions',
    'aes encryption pdf',
    'pdf security settings',
    'lock pdf files'
  ].join(', '),
  authors: [{ name: 'PDF Prodigy' }],
  creator: 'PDF Prodigy',
  publisher: 'PDF Prodigy',
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  openGraph: {
    title: 'Protect PDF Files - Add Password Protection & Security Online',
    description: 'Protect PDF files with passwords and security restrictions online for free. Add encryption and control access permissions.',
    url: 'https://pdfprodigy.com/protect-pdf',
    siteName: 'PDF Prodigy',
    images: [
      {
        url: '/images/protect-pdf-og.jpg',
        width: 1200,
        height: 630,
        alt: 'PDF Protection Tool - Add Password Security',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Protect PDF Files - Add Password Protection & Security',
    description: 'Protect PDF files with passwords and security restrictions online for free. Secure your documents with encryption.',
    images: ['/images/protect-pdf-twitter.jpg'],
    creator: '@PDFProdigy',
  },
  alternates: {
    canonical: 'https://pdfprodigy.com/protect-pdf',
  },
  category: 'PDF Tools',
  classification: 'PDF Security Tool',
  other: {
    'application-name': 'PDF Prodigy - PDF Protection Tool',
    'msapplication-TileColor': '#2563eb',
    'theme-color': '#2563eb',
  },
};
