import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Split PDF Online Free - Extract & Separate PDF Pages | PDF Prodigy',
  description: 'Split PDF files online for free. Extract specific pages, separate PDF by page ranges, or split into smaller files. No signup required. Secure PDF splitting tool.',
  keywords: [
    'split pdf online',
    'extract pdf pages',
    'separate pdf pages',
    'pdf splitter free',
    'divide pdf online',
    'pdf page extractor',
    'split pdf by pages',
    'pdf separator tool',
    'extract pages from pdf',
    'pdf page separator',
    'split pdf document',
    'pdf division tool',
    'free pdf splitter',
    'online pdf splitter',
    'pdf page splitter',
    'pdf breakup tool',
    'pdf segmentation',
    'pdf page extraction',
    'split large pdf',
    'pdf file splitter',
    'pdf splitting service',
    'secure pdf splitter',
    'pdf splitter no signup',
    'fast pdf splitting',
    'pdf page isolation'
  ],
  authors: [{ name: 'PDF Prodigy Team' }],
  creator: 'PDF Prodigy',
  publisher: 'PDF Prodigy',
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: 'https://pdfprodigy.com/split-pdf',
    title: 'Split PDF Online Free - Extract & Separate PDF Pages',
    description: 'Split PDF files online for free. Extract specific pages, separate PDF by page ranges, or split into smaller files. No signup required.',
    siteName: 'PDF Prodigy',
    images: [
      {
        url: '/images/split-pdf-og.jpg',
        width: 1200,
        height: 630,
        alt: 'Split PDF Online Free - PDF Page Extractor Tool',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Split PDF Online Free - Extract & Separate PDF Pages',
    description: 'Split PDF files online for free. Extract specific pages, separate PDF by page ranges, or split into smaller files. No signup required.',
    images: ['/images/split-pdf-twitter.jpg'],
    creator: '@pdfprodigy',
  },
  alternates: {
    canonical: 'https://pdfprodigy.com/split-pdf',
  },
  category: 'Productivity',
};
