import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Add Page Numbers to PDF - Custom PDF Page Numbering Online | PDF Prodigy',
  description: 'Add page numbers to PDF files online for free. Choose from multiple formats (1,2,3 | i,ii,iii | A,B,C), positions, and styles. Perfect for documents, reports, and presentations.',
  keywords: [
    'add page numbers to pdf',
    'pdf page numbering',
    'page numbers pdf',
    'number pdf pages',
    'pdf page numbers online',
    'add page numbers',
    'pdf numbering tool',
    'custom page numbers pdf',
    'pdf page numbering online',
    'automatic page numbering',
    'pdf page counter',
    'insert page numbers pdf',
    'pdf pagination',
    'roman numeral page numbers',
    'alphabetical page numbers',
    'numeric page numbers',
    'skip first page numbering',
    'page range numbering',
    'footer page numbers',
    'header page numbers',
    'pdf document numbering',
    'academic page numbering',
    'business document numbering',
    'legal document page numbers',
    'thesis page numbering'
  ].join(', '),
  authors: [{ name: 'PDF Prodigy' }],
  creator: 'PDF Prodigy',
  publisher: 'PDF Prodigy',
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  openGraph: {
    title: 'Add Page Numbers to PDF - Custom PDF Page Numbering Online',
    description: 'Add page numbers to PDF files online for free. Multiple formats, positions, and styles available for professional document numbering.',
    url: 'https://pdfprodigy.com/page-numbers',
    siteName: 'PDF Prodigy',
    images: [
      {
        url: '/images/page-numbers-og.jpg',
        width: 1200,
        height: 630,
        alt: 'PDF Page Numbering Tool - Add Custom Page Numbers',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Add Page Numbers to PDF - Custom PDF Page Numbering',
    description: 'Add page numbers to PDF files online for free. Multiple formats and positioning options available.',
    images: ['/images/page-numbers-twitter.jpg'],
    creator: '@PDFProdigy',
  },
  alternates: {
    canonical: 'https://pdfprodigy.com/page-numbers',
  },
  category: 'PDF Tools',
  classification: 'PDF Page Numbering Tool',
  other: {
    'application-name': 'PDF Prodigy - Page Numbers Tool',
    'msapplication-TileColor': '#9333ea',
    'theme-color': '#9333ea',
  },
};
