import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Organize PDF Pages - Reorder, Rotate, Delete & Duplicate Pages Online | PDF Prodigy',
  description: 'Organize PDF pages online for free. Reorder, rotate, duplicate, and delete PDF pages with drag-and-drop simplicity. Rearrange PDF pages instantly.',
  keywords: [
    'organize pdf pages',
    'reorder pdf pages',
    'rearrange pdf pages',
    'pdf page organizer',
    'rotate pdf pages',
    'duplicate pdf pages',
    'delete pdf pages',
    'pdf page management',
    'organize pdf online',
    'pdf page reorder',
    'rearrange pdf',
    'pdf page editor',
    'move pdf pages',
    'pdf page sorter',
    'organize pdf documents',
    'pdf page manipulation',
    'reorder pages pdf',
    'pdf page arranger',
    'sort pdf pages',
    'pdf pages tool',
    'arrange pdf pages',
    'pdf page reorganizer',
    'pdf structure editor',
    'manage pdf pages',
    'pdf page organizer tool'
  ].join(', '),
  authors: [{ name: 'PDF Prodigy' }],
  creator: 'PDF Prodigy',
  publisher: 'PDF Prodigy',
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  openGraph: {
    title: 'Organize PDF Pages - Reorder, Rotate, Delete & Duplicate Pages Online',
    description: 'Organize PDF pages online for free. Reorder, rotate, duplicate, and delete PDF pages with intuitive drag-and-drop interface.',
    url: 'https://pdfprodigy.com/organize-pdf',
    siteName: 'PDF Prodigy',
    images: [
      {
        url: '/images/organize-pdf-og.jpg',
        width: 1200,
        height: 630,
        alt: 'PDF Page Organizer Tool - Reorder and Manage Pages',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Organize PDF Pages - Reorder, Rotate, Delete & Duplicate Pages',
    description: 'Organize PDF pages online for free. Reorder, rotate, duplicate, and delete PDF pages instantly.',
    images: ['/images/organize-pdf-twitter.jpg'],
    creator: '@PDFProdigy',
  },
  alternates: {
    canonical: 'https://pdfprodigy.com/organize-pdf',
  },
  category: 'PDF Tools',
  classification: 'PDF Page Management Tool',
  other: {
    'application-name': 'PDF Prodigy - PDF Page Organizer',
    'msapplication-TileColor': '#3b82f6',
    'theme-color': '#3b82f6',
  },
};
