import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Compress PDF Online Free - Reduce PDF File Size | PDF Prodigy',
  description: 'Compress PDF files online for free. Reduce PDF file size while maintaining quality. Choose compression levels, advanced settings, and optimize your PDFs instantly.',
  keywords: [
    'compress pdf online',
    'reduce pdf file size',
    'pdf compressor free',
    'shrink pdf online',
    'pdf size reducer',
    'compress pdf file',
    'pdf optimization tool',
    'reduce pdf size online',
    'pdf file compressor',
    'online pdf compressor',
    'free pdf compression',
    'pdf size optimizer',
    'compress large pdf',
    'pdf compression service',
    'minimize pdf size',
    'pdf file size reducer',
    'compress pdf without losing quality',
    'pdf compression levels',
    'optimize pdf online',
    'pdf file optimizer',
    'secure pdf compressor',
    'pdf compressor no signup',
    'fast pdf compression',
    'professional pdf optimizer',
    'bulk pdf compression'
  ],
  authors: [{ name: 'PDF Prodigy Team' }],
  creator: 'PDF Prodigy',
  publisher: 'PDF Prodigy',
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: 'https://pdfprodigy.com/compress-pdf',
    title: 'Compress PDF Online Free - Reduce PDF File Size',
    description: 'Compress PDF files online for free. Reduce PDF file size while maintaining quality. Multiple compression levels and advanced optimization settings.',
    siteName: 'PDF Prodigy',
    images: [
      {
        url: '/images/compress-pdf-og.jpg',
        width: 1200,
        height: 630,
        alt: 'Compress PDF Online Free - PDF File Size Reducer',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Compress PDF Online Free - Reduce PDF File Size',
    description: 'Compress PDF files online for free. Reduce PDF file size while maintaining quality. Multiple compression levels available.',
    images: ['/images/compress-pdf-twitter.jpg'],
    creator: '@pdfprodigy',
  },
  alternates: {
    canonical: 'https://pdfprodigy.com/compress-pdf',
  },
  category: 'Productivity',
};
